// weight_rom.v
// Weight ROM for one CNN layer.
// Width: MAX_C * WWIDTH = 16 * 16 = 256 bits  (all output channels in parallel)
// Depth: C_IN * 9                              (inner_addr = ci*9 + kh*3 + kw)
// Read latency: 1 clock cycle (registered output)
//
// Initialized from a .mem file generated by tools/extract_weights.py.
// The .mem file has one 16-bit entry per line, organized as:
//   [inner_addr=0, co=0], [inner_addr=0, co=1], ... [inner_addr=0, co=15],
//   [inner_addr=1, co=0], ...

`timescale 1ns/1ps
module weight_rom #(
    parameter MAX_C     = 16,           // parallel output channels
    parameter WWIDTH    = 16,           // weight bit width (Q3.12)
    parameter C_IN      = 8,            // input channels for this layer
    parameter DEPTH     = C_IN * 9,     // total inner addresses
    parameter INIT_FILE = "weights_L2_conv.mem"
)(
    input  wire                       clk,
    // Inner address: ci*9 + kh*3 + kw
    input  wire [$clog2(DEPTH)-1:0]   addr,
    // All MAX_C weights for current inner_addr, one per output channel
    output reg  [MAX_C*WWIDTH-1:0]    dout
);

// Flat ROM: DEPTH*MAX_C entries of WWIDTH bits
(* rom_style = "block" *)
reg [WWIDTH-1:0] rom [0:DEPTH*MAX_C-1];

initial $readmemh(INIT_FILE, rom);

integer i;
reg [MAX_C*WWIDTH-1:0] row;

always @(posedge clk) begin
    // Read MAX_C consecutive entries starting at addr*MAX_C
    // (synthesis tool handles this as a wide word read)
    for (i = 0; i < MAX_C; i = i + 1)
        row[i*WWIDTH +: WWIDTH] <= rom[addr * MAX_C + i];
    dout <= row;
end

endmodule


// bias_rom.v — separate small ROM for biases (Q6.24, 32-bit)
module bias_rom #(
    parameter MAX_C     = 16,
    parameter BWIDTH    = 32,
    parameter INIT_FILE = "biases_L2_conv.mem"
)(
    input  wire                clk,
    input  wire [3:0]          addr,
    output reg  [BWIDTH-1:0]   dout
);

(* rom_style = "distributed" *)
reg [BWIDTH-1:0] rom [0:MAX_C-1];
initial $readmemh(INIT_FILE, rom);
always @(posedge clk) dout <= rom[addr];

endmodule
